name: Build and Deploy to VM
on:
  push:
    branches:
      - test/devops
  pull_request:
    types: [closed]
    branches:
      - main
      - cloud-deploy

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4  
              
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                context: ./src
                push: true
                tags: sandside/myflix:thumbnails

    # deploy:
    #     needs: build
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Pull and Run Image in VM
    #           uses: appleboy/ssh-action@master
    #           with:
    #             host: ${{ secrets.VM_IP }}
    #             username: ${{ secrets.VM_USERNAME }}
    #             key: ${{ secrets.VM_SSH_KEY }}
    #             script: |
    #               docker stop myflix-thumbnails
    #               docker rm myflix-thumbnails
    #               docker pull sandside/myflix:thumbnails
    #               docker run -d -p 80:80 --restart=always --name myflix-thumbnails sandside/myflix:thumbnails